version: "3.9"
services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./sensors.db}
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
